# GraphRAG SDK — Discovery: ontology catalogs
#
# A Catalog is a *source of truth* for ontology vocabulary: given a
# type name (``"Person"``), it returns that type's schema —
# attributes, relations to other types, canonical URI. The catalog
# decouples discovery from any particular vocabulary; the grounded
# discovery path (``Ontology.from_sources(method="grounded")``) takes a
# catalog as a parameter, runs NER to learn which types the corpus
# contains, and asks the catalog for the schema of those types.
#
# The bundled :class:`SchemaOrgCatalog` reads a JSON snapshot of
# Schema.org's published vocabulary that's generated by
# ``scripts/generate_schema_org_data.py`` from the live
# https://schema.org/version/latest/schemaorg-current-https.jsonld
# endpoint. The data is real Schema.org-derived; the SDK only chooses
# which subset to bundle.

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from collections.abc import Iterable
from importlib import resources
from pathlib import Path

from graphrag_sdk.core.models import Attribute, Entity, Relation


class Catalog(ABC):
    """A source-of-truth ontology vocabulary the grounded pipeline can query.

    Concrete implementations may consult a bundled snapshot, a live web
    endpoint, a SPARQL store, a domain catalog the user wrote — the
    abstraction lets ``Ontology.from_sources(method="grounded")`` work
    against any vocabulary without knowing where it came from.
    """

    @abstractmethod
    def known_types(self) -> set[str]:
        """Every type name this catalog can answer about."""

    @abstractmethod
    def lookup(self, type_name: str) -> Entity | None:
        """Return the catalog's view of ``type_name``, or ``None`` if unknown.

        The returned :class:`Entity` includes the type's attributes
        (translated to the SDK's typed-property model) and its
        ``description`` field carries the catalog's natural-language
        description. The canonical source URI, when the catalog has
        one, is recorded in ``description`` for traceability.
        """

    @abstractmethod
    def relations_among(self, type_names: Iterable[str]) -> list[Relation]:
        """All relations whose source AND target labels are in ``type_names``.

        The grounded pipeline calls this after collecting the set of
        types the corpus contains, to pull only the relations relevant
        to that subset. Patterns are merged by relation label.
        """


# ── SchemaOrgCatalog ───────────────────────────────────────────────


def _bundled_schema_org_path() -> Path:
    """Resolve the bundled Schema.org JSON file shipped with the SDK."""
    try:
        ref = resources.files("graphrag_sdk").joinpath("data/schema_org.json")
        return Path(str(ref))
    except (ModuleNotFoundError, FileNotFoundError):
        # Editable install fallback.
        return Path(__file__).resolve().parent.parent / "data" / "schema_org.json"


class SchemaOrgCatalog(Catalog):
    """Catalog backed by a bundled Schema.org JSON-LD subset.

    The data file ``graphrag_sdk/data/schema_org.json`` is generated by
    ``scripts/generate_schema_org_data.py`` from the live Schema.org
    vocabulary endpoint. No network at runtime — load is lazy and
    cached in process.

    Example::

        from graphrag_sdk import Ontology
        from graphrag_sdk.discovery.catalog import SchemaOrgCatalog

        catalog = SchemaOrgCatalog()
        catalog.known_types()             # {"Person", "Organization", ...}
        catalog.lookup("Person")          # Entity(label="Person", properties=[...])
        catalog.relations_among({"Person", "Organization"})
        #   → [Relation(label="WORKS_FOR", patterns=[("Person", "Organization")]), ...]

    To use against a non-default snapshot (e.g. a richer subset
    generated locally), pass an explicit ``path``::

        SchemaOrgCatalog(path="/my/regen/schema_org.json")
    """

    def __init__(self, *, path: str | Path | None = None) -> None:
        self._path = Path(path) if path is not None else _bundled_schema_org_path()
        self._raw: dict | None = None

    def _load(self) -> dict:
        if self._raw is None:
            self._raw = json.loads(self._path.read_text(encoding="utf-8"))
        return self._raw

    def known_types(self) -> set[str]:
        return set(self._load()["types"].keys())

    def lookup(self, type_name: str) -> Entity | None:
        raw_types = self._load()["types"]
        type_record = raw_types.get(type_name)
        if type_record is None:
            return None

        properties: list[Attribute] = []
        for p in type_record["properties"]:
            schema_name = p.get("schema_name", p["name"])
            base_desc = p.get("description") or ""
            attr_desc = f"Schema.org {schema_name}"
            if base_desc:
                attr_desc = f"{attr_desc} — {base_desc}"
            properties.append(
                Attribute(
                    name=p["name"],
                    type=p["type"],
                    description=attr_desc,
                )
            )

        description = type_record.get("description") or ""
        uri = type_record.get("canonical_uri")
        if uri:
            description = (
                f"{description} (Schema.org: {uri})" if description else f"Schema.org: {uri}"
            )

        return Entity(
            label=type_record["label"],
            description=description or None,
            properties=properties,
        )

    def relations_among(self, type_names: Iterable[str]) -> list[Relation]:
        wanted = set(type_names)
        raw = self._load()
        # Group by label so a relation with multiple patterns becomes one Relation.
        by_label: dict[str, dict] = {}
        for rec in raw["relations"]:
            source, target = rec["source"], rec["target"]
            if source not in wanted or target not in wanted:
                continue
            entry = by_label.setdefault(
                rec["label"],
                {
                    "patterns": [],
                    "schema_name": rec.get("schema_name"),
                    "description": rec.get("description") or "",
                },
            )
            pattern = (source, target)
            if pattern not in entry["patterns"]:
                entry["patterns"].append(pattern)

        relations: list[Relation] = []
        for label, entry in sorted(by_label.items()):
            schema_name = entry["schema_name"] or label
            base_desc = entry["description"]
            desc = f"Schema.org {schema_name}"
            if base_desc:
                desc = f"{desc} — {base_desc}"
            relations.append(
                Relation(
                    label=label,
                    description=desc,
                    patterns=entry["patterns"],
                )
            )
        return relations
