name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    defaults:
      run:
        working-directory: graphrag_sdk
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install build

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: graphrag_sdk/dist/
