name: Run tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    services:
      falkordb:
        image: falkordb/falkordb:latest
        ports:
          - 6379:6379
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        volumes:
          - ollama:/root/.ollama
    
    strategy:
      matrix:
        model: [openai/gpt-4.1] # List of models

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.11.0 # Update with desired Python version

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - id: "auth"
        uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3"
        with:
          version: ">= 363.0.0"

      - name: Install dependencies
        run: uv sync --extra test

      - name: Wait for Ollama to be ready
        run: |
          until curl -s http://localhost:11434; do
            echo "Waiting for Ollama..."
            sleep 10
          done

      - name: Run tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REGION: ${{ vars.REGION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          TEST_MODEL: ${{ matrix.model }} # Pass the model as an environment variable
        run: uv run pytest
